### ISSUE TITLE
Suggestion: even though the git itself is the release, pack a release to make downloading a little bit easier

### ISSUE THREAD

**Issue by drakomatic** [altoiddealer/ad_discordbot#67]
Make a release please

**Comment by altoiddealer** [comment]
Thanks for sticking with the bot all this time, and I appreciate all Issue reports / feedback.

Quick note: This project is now being co-developed (so you understand my usage of “We”)

We made an alternate Regenerate function that creates new responses instead of instantly replacing the original response.  We are in the process of implementing a system to easily choose your favorite response from these responses, to be the replacement in history.

After this will be a great time to publish first Release, this has been in the back of my mind for awhile, thanks for the reminder

**Comment by altoiddealer** [comment]
Still working on this, there's a few more steps to it than you may think :P

**Comment by altoiddealer** [comment]
Finally made a release!
